"""
Auth Ports

Architectural Intent:
- Interfaces for authentication and token management
- Defined in domain layer, implemented in infrastructure
"""
from __future__ import annotations

from typing import Protocol

from src.domain.entities.user import User
from src.domain.value_objects.auth import TokenClaims


class TokenPort(Protocol):
    def create_access_token(self, claims: TokenClaims) -> str: ...
    def create_refresh_token(self, claims: TokenClaims) -> str: ...
    def verify_token(self, token: str) -> TokenClaims | None: ...


class PasswordPort(Protocol):
    def hash_password(self, password: str) -> str: ...
    def verify_password(self, password: str, password_hash: str) -> bool: ...


class UserRepositoryPort(Protocol):
    async def save(self, user: User) -> None: ...
    async def get_by_id(self, id: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def list_all(self) -> list[User]: ...
    async def delete(self, id: str) -> None: ...
