"""
Repository Ports

Architectural Intent:
- Interfaces for aggregate persistence
- Defined in domain layer, implemented in infrastructure
- One repository per aggregate root
"""
from __future__ import annotations

from typing import Protocol

from src.domain.entities.mapping_config import MappingConfiguration
from src.domain.entities.pipeline import Pipeline
from src.domain.entities.source_connection import SourceConnection


class SourceConnectionRepositoryPort(Protocol):
    async def save(self, connection: SourceConnection) -> None: ...
    async def get_by_id(self, id: str) -> SourceConnection | None: ...
    async def list_all(self) -> list[SourceConnection]: ...
    async def delete(self, id: str) -> None: ...


class MappingConfigRepositoryPort(Protocol):
    async def save(self, config: MappingConfiguration) -> None: ...
    async def get_by_id(self, id: str) -> MappingConfiguration | None: ...
    async def list_all(self) -> list[MappingConfiguration]: ...
    async def delete(self, id: str) -> None: ...


class PipelineRepositoryPort(Protocol):
    async def save(self, pipeline: Pipeline) -> None: ...
    async def get_by_id(self, id: str) -> Pipeline | None: ...
    async def list_all(self) -> list[Pipeline]: ...
    async def delete(self, id: str) -> None: ...


class EventBusPort(Protocol):
    async def publish(self, events: list) -> None: ...
